<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpar dados relacionados primeiro
        Employee::query()->delete();
        User::whereIn('email', [
            'joao.silva@organization.pt',
            'maria.santos@organization.pt',
            'pedro.oliveira@organization.pt',
            'ana.costa@organization.pt',
            'carlos.ferreira@organization.pt',
            'isabel.martins@organization.pt',
            'ricardo.alves@organization.pt',
            'fernanda.gomes@organization.pt',
            'paulo.rocha@organization.pt',
            'tiago.neves@organization.pt',
            'bruno.mendes@organization.pt',
            'sophia.pinto@organization.pt',
            'andre.lopes@organization.pt',
            'mariana.teixeira@organization.pt',
        ])->delete();

        // Buscar IDs dinamicamente ao invés de hardcodificar
        $units = DB::table('organizational_units')
            ->pluck('id', 'name')
            ->toArray();

        $designations = DB::table('designations')
            ->pluck('id', 'name')
            ->toArray();

        $employees = [
            [
                'city_id' => 3,
                'unit_id' => $units['Direção Geral'],
                'designation_id' => $designations['Diretor'],
                'first_name' => 'João',
                'last_name' => 'Silva',
                'email' => 'joao.silva@organization.pt',
                'phone_number' => '+351912345678',
                'date_of_birth' => '1965-05-15',
                'nif' => '123456789',
                'nss' => '10000000000',
                'address' => 'Rua Principal 100, Port Blair',
                'zip_code' => '12345-001',
                'date_hired' => '2010-01-15',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Departamento de Recursos Humanos'],
                'designation_id' => $designations['Chefe de Departamento'],
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'email' => 'maria.santos@organization.pt',
                'phone_number' => '+351913456789',
                'date_of_birth' => '1975-08-22',
                'nif' => '223456789',
                'nss' => '10000000001',
                'address' => 'Avenida Central 250, Port Blair',
                'zip_code' => '12345-002',
                'date_hired' => '2015-03-01',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Recrutamento e Seleção'],
                'designation_id' => $designations['Técnico Sênior'],
                'first_name' => 'Pedro',
                'last_name' => 'Oliveira',
                'email' => 'pedro.oliveira@organization.pt',
                'phone_number' => '+351914567890',
                'date_of_birth' => '1985-03-10',
                'nif' => '323456789',
                'nss' => '10000000002',
                'address' => 'Rua Lateral 45, Port Blair',
                'zip_code' => '12345-003',
                'date_hired' => '2018-06-15',
                'date_dismissed' => null,
                'vacation_balance' => 18,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Formação e Desenvolvimento'],
                'designation_id' => $designations['Técnico Pleno'],
                'first_name' => 'Ana',
                'last_name' => 'Costa',
                'email' => 'ana.costa@organization.pt',
                'phone_number' => '+351915678901',
                'date_of_birth' => '1990-11-28',
                'nif' => '423456789',
                'nss' => '10000000003',
                'address' => 'Rua das Flores 88, Port Blair',
                'zip_code' => '12345-004',
                'date_hired' => '2020-01-10',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Departamento de Operações'],
                'designation_id' => $designations['Chefe de Departamento'],
                'first_name' => 'Carlos',
                'last_name' => 'Ferreira',
                'email' => 'carlos.ferreira@organization.pt',
                'phone_number' => '+351916789012',
                'date_of_birth' => '1972-07-05',
                'nif' => '523456789',
                'nss' => '10000000004',
                'address' => 'Avenida Industrial 500, Port Blair',
                'zip_code' => '12345-005',
                'date_hired' => '2012-04-20',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Qualidade e Conformidade'],
                'designation_id' => $designations['Especialista'],
                'first_name' => 'Isabel',
                'last_name' => 'Martins',
                'email' => 'isabel.martins@organization.pt',
                'phone_number' => '+351917890123',
                'date_of_birth' => '1988-02-14',
                'nif' => '623456789',
                'nss' => '10000000005',
                'address' => 'Rua da Qualidade 12, Port Blair',
                'zip_code' => '12345-006',
                'date_hired' => '2019-09-01',
                'date_dismissed' => null,
                'vacation_balance' => 20,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Departamento Financeiro'],
                'designation_id' => $designations['Chefe de Departamento'],
                'first_name' => 'Ricardo',
                'last_name' => 'Alves',
                'email' => 'ricardo.alves@organization.pt',
                'phone_number' => '+351918901234',
                'date_of_birth' => '1970-09-18',
                'nif' => '723456789',
                'nss' => '10000000006',
                'address' => 'Avenida Financeira 300, Port Blair',
                'zip_code' => '12345-007',
                'date_hired' => '2011-02-01',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Contabilidade'],
                'designation_id' => $designations['Técnico Sênior'],
                'first_name' => 'Fernanda',
                'last_name' => 'Gomes',
                'email' => 'fernanda.gomes@organization.pt',
                'phone_number' => '+351919012345',
                'date_of_birth' => '1987-12-03',
                'nif' => '823456789',
                'nss' => '10000000007',
                'address' => 'Rua Contábil 77, Port Blair',
                'zip_code' => '12345-008',
                'date_hired' => '2017-05-15',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Tesouraria'],
                'designation_id' => $designations['Técnico Pleno'],
                'first_name' => 'Paulo',
                'last_name' => 'Rocha',
                'email' => 'paulo.rocha@organization.pt',
                'phone_number' => '+351920123456',
                'date_of_birth' => '1992-04-09',
                'nif' => '923456789',
                'nss' => '10000000008',
                'address' => 'Rua Tesouraria 25, Port Blair',
                'zip_code' => '12345-009',
                'date_hired' => '2021-03-01',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Departamento de Tecnologia'],
                'designation_id' => $designations['Subdiretor'],
                'first_name' => 'Tiago',
                'last_name' => 'Neves',
                'email' => 'tiago.neves@organization.pt',
                'phone_number' => '+351921234567',
                'date_of_birth' => '1978-06-21',
                'nif' => '1023456789',
                'nss' => '10000000009',
                'address' => 'Avenida Tech 999, Port Blair',
                'zip_code' => '12345-010',
                'date_hired' => '2013-08-01',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Infraestrutura'],
                'designation_id' => $designations['Técnico Sênior'],
                'first_name' => 'Bruno',
                'last_name' => 'Mendes',
                'email' => 'bruno.mendes@organization.pt',
                'phone_number' => '+351922345678',
                'date_of_birth' => '1989-01-30',
                'nif' => '1123456789',
                'nss' => '10000000010',
                'address' => 'Rua Servidores 150, Port Blair',
                'zip_code' => '12345-011',
                'date_hired' => '2019-02-15',
                'date_dismissed' => null,
                'vacation_balance' => 20,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Desenvolvimento de Software'],
                'designation_id' => $designations['Especialista'],
                'first_name' => 'Sophia',
                'last_name' => 'Pinto',
                'email' => 'sophia.pinto@organization.pt',
                'phone_number' => '+351923456789',
                'date_of_birth' => '1991-10-12',
                'nif' => '1223456789',
                'nss' => '10000000011',
                'address' => 'Rua Código 200, Port Blair',
                'zip_code' => '12345-012',
                'date_hired' => '2020-07-01',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Desenvolvimento de Software'],
                'designation_id' => $designations['Técnico Pleno'],
                'first_name' => 'André',
                'last_name' => 'Lopes',
                'email' => 'andre.lopes@organization.pt',
                'phone_number' => '+351924567890',
                'date_of_birth' => '1994-05-20',
                'nif' => '1323456789',
                'nss' => '10000000012',
                'address' => 'Rua Desenvolvimento 333, Port Blair',
                'zip_code' => '12345-013',
                'date_hired' => '2022-01-10',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
            [
                'city_id' => 3,
                'unit_id' => $units['Secção de Suporte Técnico'],
                'designation_id' => $designations['Técnico Junior'],
                'first_name' => 'Mariana',
                'last_name' => 'Teixeira',
                'email' => 'mariana.teixeira@organization.pt',
                'phone_number' => '+351925678901',
                'date_of_birth' => '1997-08-07',
                'nif' => '1423456789',
                'nss' => '10000000013',
                'address' => 'Rua Suporte 88, Port Blair',
                'zip_code' => '12345-014',
                'date_hired' => '2023-02-01',
                'date_dismissed' => null,
                'vacation_balance' => 22,
            ],
        ];

        // Usar Employee::create() para disparar o observer
        foreach ($employees as $employeeData) {
            Employee::create($employeeData);
        }
    }
}
